name: node

on: push 

jobs: 
 package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: package
            path: "*.tgz"
            
 publish:
 
    name: "Publish to GitHub Packages"
    needs: [package]
    runs-on: ubuntu-latest
   
    steps:
    - name: Upload
      uses: actions/download-artifact@v2
      with:
          name: package
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: '@rahulmalewadi'
    
    - run: npm publish 
      env:
        NODE_AUTH_TOKEN: ${{secrets.PAT_TOKEN}}
